colors:
  - [189, 16, 224]
  - [0, 128, 255]
  - [3, 211, 104]
  - [139, 213, 77]
names: [mass, filter, splitter, rollers]
nc: 4
train: ./datasets_chute1/images/train
val: ./datasets_chute1/images/val
